import { EventForm } from "@/components/crm/event-form"
import { PageHeader } from "@/components/crm/page-header"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { createClient } from "@/lib/supabase/server"
import { formatDate } from "@/lib/utils"

const statusLabel: Record<string,string> = { hold:"Apartado", visit:"Visita", confirmed:"Confirmado", blocked:"Bloqueado" }
export default async function CalendarPage() { const supabase=await createClient(); const first=new Date(); first.setDate(1); const start=first.toISOString().slice(0,10); const last=new Date(first.getFullYear(),first.getMonth()+1,0); const end=last.toISOString().slice(0,10); const {data}=await supabase.from("venue_events").select("id,title,event_date,start_time,status,notes").gte("event_date",start).lte("event_date",end).order("event_date"); const events=data??[]; const offset=(first.getDay()+6)%7; const days=Array.from({length:offset+last.getDate()},(_,index)=>index<offset?null:index-offset+1)
return <div className="flex flex-col gap-6 p-4 md:p-6 lg:p-8"><PageHeader eyebrow="Disponibilidad" title={first.toLocaleDateString("es-MX",{month:"long",year:"numeric"})} description="Una sola vista para apartados, visitas y celebraciones confirmadas." action={<EventForm/>}/><div className="grid gap-6 xl:grid-cols-[1fr_320px]"><Card><CardContent className="p-3 sm:p-5"><div className="grid grid-cols-7 gap-px overflow-hidden rounded-lg bg-border">{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map((day)=><div key={day} className="bg-muted p-2 text-center text-xs text-muted-foreground">{day}</div>)}{days.map((day,index)=>{ const dayEvents=day?events.filter((event)=>Number(event.event_date.slice(-2))===day):[]; return <div key={index} className="min-h-24 bg-card p-2 sm:min-h-28"><span className="text-xs text-muted-foreground">{day}</span><div className="mt-2 flex flex-col gap-1">{dayEvents.map((event)=><div key={event.id} className="truncate rounded bg-secondary px-2 py-1 text-xs text-primary" title={event.title}>{event.title}</div>)}</div></div>})}</div></CardContent></Card><Card><CardHeader><CardTitle>Fechas del mes</CardTitle></CardHeader><CardContent className="flex flex-col gap-4">{events.map((event)=><div key={event.id} className="border-b pb-4 last:border-0"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-medium">{event.title}</p><p className="mt-1 text-xs text-muted-foreground">{formatDate(event.event_date+"T12:00:00")}{event.start_time?` · ${event.start_time.slice(0,5)}`:""}</p></div><Badge variant="secondary">{statusLabel[event.status]}</Badge></div></div>)}{!events.length&&<p className="text-sm text-muted-foreground">No hay fechas registradas este mes.</p>}</CardContent></Card></div></div> }
