import { Download } from "lucide-react"
import { PageHeader } from "@/components/crm/page-header"
import { QuoteForm } from "@/components/crm/quote-form"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table"
import { createClient } from "@/lib/supabase/server"
import { formatDate,formatMoney } from "@/lib/utils"
const labels:Record<string,string>={draft:"Borrador",sent:"Enviada",accepted:"Aceptada",expired:"Vencida",cancelled:"Cancelada"}
export default async function QuotesPage(){const supabase=await createClient();const{data}=await supabase.from("quotes").select("id,folio,status,event_date,total_cents,valid_until,created_at,customers(name)").order("created_at",{ascending:false});const rows=data??[];return <div className="flex flex-col gap-6 p-4 md:p-6 lg:p-8"><PageHeader eyebrow="Propuestas" title="Cotizaciones" description="Crea, descarga y da seguimiento a cada propuesta comercial." action={<QuoteForm/>}/><div className="overflow-hidden rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Folio</TableHead><TableHead>Cliente</TableHead><TableHead>Evento</TableHead><TableHead>Total</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">PDF</TableHead></TableRow></TableHeader><TableBody>{rows.map((quote)=>{const customer=Array.isArray(quote.customers)?quote.customers[0]:quote.customers;return <TableRow key={quote.id}><TableCell className="font-mono text-xs">{quote.folio}</TableCell><TableCell className="font-medium">{customer?.name??"Cliente"}</TableCell><TableCell>{quote.event_date?formatDate(quote.event_date+"T12:00:00"):"Por definir"}</TableCell><TableCell>{formatMoney(quote.total_cents)}</TableCell><TableCell><Badge variant="secondary">{labels[quote.status]}</Badge></TableCell><TableCell className="text-right"><Button size="icon" variant="ghost" asChild><a href={`/api/quotes/${quote.id}/pdf`}><Download/><span className="sr-only">Descargar PDF</span></a></Button></TableCell></TableRow>})}{!rows.length&&<TableRow><TableCell colSpan={6} className="h-32 text-center text-muted-foreground">Crea tu primera cotización para verla aquí.</TableCell></TableRow>}</TableBody></Table></div></div>}
