"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"
import { Pencil } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card"
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog"
import { Field,FieldGroup,FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { formatMoney } from "@/lib/utils"
type CatalogItem={id:string;name:string;description:string;price_cents:number;active:boolean;featured?:boolean;unit?:string;inclusions?:string[]}
export function CatalogEditor({packages,services}:{packages:CatalogItem[];services:CatalogItem[]}){return <div className="grid gap-6 xl:grid-cols-2"><CatalogGroup title="Paquetes" description="Propuestas visibles en el sitio público." type="packages" items={packages}/><CatalogGroup title="Servicios" description="Conceptos disponibles para cotizaciones." type="services" items={services}/></div>}
function CatalogGroup({title,description,type,items}:{title:string;description:string;type:string;items:CatalogItem[]}){return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{items.map((item)=><Editor key={item.id} item={item} type={type}/>)}</CardContent></Card>}
function Editor({item,type}:{item:CatalogItem;type:string}){const[open,setOpen]=useState(false);const router=useRouter();async function submit(formData:FormData){const res=await fetch(`/api/catalog/${type}/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(formData))});if(res.ok){toast.success("Catálogo actualizado");setOpen(false);router.refresh()}else toast.error("No se pudo guardar")}return <div className="flex items-center justify-between rounded-lg border p-4"><div className="min-w-0"><p className="font-medium">{item.name}</p><p className="mt-1 truncate text-xs text-muted-foreground">{item.price_cents?formatMoney(item.price_cents):"Precio por definir"}{item.unit?` · por ${item.unit}`:""}</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="icon" variant="ghost"><Pencil/><span className="sr-only">Editar {item.name}</span></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle className="font-serif text-3xl">Editar {item.name}</DialogTitle><DialogDescription>Los cambios del paquete se reflejan en la experiencia pública.</DialogDescription></DialogHeader><form action={submit}><FieldGroup><Field><FieldLabel htmlFor={`name-${item.id}`}>Nombre</FieldLabel><Input id={`name-${item.id}`} name="name" defaultValue={item.name} required/></Field><Field><FieldLabel htmlFor={`description-${item.id}`}>Descripción</FieldLabel><Textarea id={`description-${item.id}`} name="description" defaultValue={item.description}/></Field><Field><FieldLabel htmlFor={`price-${item.id}`}>Precio base (MXN)</FieldLabel><Input id={`price-${item.id}`} name="price" type="number" min="0" defaultValue={item.price_cents/100}/></Field>{type==="packages"&&<Field><FieldLabel htmlFor={`inclusions-${item.id}`}>Incluye (una línea por concepto)</FieldLabel><Textarea id={`inclusions-${item.id}`} name="inclusions" defaultValue={item.inclusions?.join("\n")}/></Field>}<Button>Guardar cambios</Button></FieldGroup></form></DialogContent></Dialog></div>}
