"use client"
import { useState } from "react"
import { useChat } from "@ai-sdk/react"
import { DefaultChatTransport } from "ai"
import { ArrowUp,Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card,CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"
const transport=new DefaultChatTransport({api:"/api/internal-chat"})
export function InternalAssistant(){const[input,setInput]=useState("");const{messages,sendMessage,status}=useChat({transport});const busy=status==="submitted"||status==="streaming";const prompts=["Resume mis solicitudes recientes","¿Qué seguimientos debo priorizar?","Ayúdame a redactar una respuesta para una boda"]
return <Card className="mx-auto w-full max-w-4xl overflow-hidden"><div className="flex items-center gap-3 border-b bg-primary p-5 text-primary-foreground"><span className="flex size-10 items-center justify-center rounded-full bg-primary-foreground/10"><Sparkles className="size-5"/></span><div><p className="font-medium">Copiloto Parlovento</p><p className="text-xs text-primary-foreground/65">Contexto operativo y ayuda para responder</p></div></div><CardContent className="p-0"><div className="flex min-h-[430px] flex-col gap-4 p-5" aria-live="polite"><div className="max-w-2xl rounded-xl bg-muted p-4 text-sm leading-relaxed">Puedo ayudarte a revisar prioridades, resumir el pipeline o preparar mensajes para clientes. No enviaré nada sin tu confirmación.</div>{messages.map(message=><div key={message.id} className={cn("max-w-2xl rounded-xl p-4 text-sm leading-relaxed",message.role==="user"?"ml-auto bg-primary text-primary-foreground":"bg-muted")}>{message.parts.map((part,index)=>part.type==="text"?<span key={index}>{part.text}</span>:null)}</div>)}{busy&&<p className="text-sm text-muted-foreground">Analizando…</p>} {!messages.length&&<div className="mt-auto flex flex-wrap gap-2">{prompts.map(prompt=><Button key={prompt} variant="outline" size="sm" onClick={()=>sendMessage({text:prompt})}>{prompt}</Button>)}</div>}</div><form className="flex gap-2 border-t p-4" onSubmit={event=>{event.preventDefault();if(input.trim()&&!busy){sendMessage({text:input});setInput("")}}}><Input value={input} onChange={event=>setInput(event.target.value)} placeholder="Pregunta sobre la operación…" disabled={busy} onKeyDown={event=>{if(event.nativeEvent.isComposing||event.keyCode===229)return}}/><Button size="icon" disabled={!input.trim()||busy}><ArrowUp/><span className="sr-only">Enviar</span></Button></form></CardContent></Card>}
