"use client"

import Image from "next/image"
import Link from "next/link"
import { useState } from "react"
import { ArrowRight, CalendarDays, Check, Leaf, MapPin, Users } from "lucide-react"
import { PublicHeader } from "@/components/public-header"
import { InquiryForm } from "@/components/inquiry-form"
import { ChatAssistant } from "@/components/chat-assistant"
import { BrandMark } from "@/components/brand-mark"
import { Button } from "@/components/ui/button"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export type PublicPackage = { id: string; name: string; description: string; featured: boolean; inclusions: string[] }
export type PublicFaq = { id: string; question: string; answer: string }

export function PublicHome({ packages, faqs }: { packages: PublicPackage[]; faqs: PublicFaq[] }) {
  const [quoteOpen, setQuoteOpen] = useState(false)
  const openQuote = () => setQuoteOpen(true)
  return <main>
    <section className="relative min-h-[760px] overflow-hidden bg-foreground text-primary-foreground">
      <Image src="/images/parlovento-hero.png" alt="Jardín y palapa de Parlovento iluminados para una recepción" fill priority className="object-cover" sizes="100vw" />
      <div className="absolute inset-0 bg-foreground/65" />
      <div className="absolute inset-0 bg-gradient-to-r from-foreground/70 via-foreground/20 to-transparent" />
      <PublicHeader onQuote={openQuote} />
      <div className="relative mx-auto flex min-h-[760px] max-w-7xl items-end px-5 pb-20 pt-32 lg:px-8 lg:pb-24">
        <div className="max-w-3xl animate-rise"><p className="mb-5 flex items-center gap-2 text-sm font-medium uppercase tracking-[0.2em] text-accent"><Leaf className="size-4" />Salón jardín para eventos</p><h1 className="text-balance font-serif text-6xl font-semibold leading-[0.95] tracking-tight sm:text-7xl lg:text-8xl">Hay momentos que merecen su propio lugar.</h1><p className="mt-6 max-w-xl text-pretty text-lg leading-relaxed text-primary-foreground/80">Parlovento reúne jardín, palapa y una atmósfera cálida para transformar tu celebración en un recuerdo que se queda.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" onClick={openQuote} className="bg-accent text-accent-foreground hover:bg-accent/90">Planea tu evento<ArrowRight data-icon="inline-end" /></Button><Button size="lg" variant="outline" asChild className="border-primary-foreground/35 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><Link href="#espacios">Conoce el espacio</Link></Button></div></div>
      </div>
      <div className="absolute bottom-0 right-0 hidden border-l border-t border-primary-foreground/20 bg-foreground/55 p-6 backdrop-blur md:block"><div className="flex gap-8"><div><p className="font-serif text-3xl">450</p><p className="text-xs text-primary-foreground/65">personas</p></div><div><p className="font-serif text-3xl">3</p><p className="text-xs text-primary-foreground/65">ambientes</p></div></div></div>
    </section>

    <section id="espacios" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid items-center gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">El lugar</p><h2 className="mt-4 text-balance font-serif text-5xl font-semibold leading-tight sm:text-6xl">Entre árboles, luces y conversaciones largas.</h2><p className="mt-6 max-w-lg leading-relaxed text-muted-foreground">Un espacio versátil que acompaña cada parte de tu evento: bienvenida en el jardín, celebración bajo la palapa y rincones que se sienten propios.</p><div className="mt-8 grid gap-5 sm:grid-cols-3 lg:grid-cols-1"><Feature icon={Users} title="Hasta 450 personas" text="Montajes adaptables a cada celebración." /><Feature icon={CalendarDays} title="Agenda interna" text="Consulta fechas y coordina una visita." /><Feature icon={MapPin} title="Jardín + palapa" text="Ambientes conectados en un solo recinto." /></div></div><div className="grid grid-cols-5 gap-4"><div className="relative col-span-3 min-h-[520px] overflow-hidden rounded-2xl"><Image src="/images/parlovento-garden.png" alt="Jardín preparado para una ceremonia" fill className="object-cover" sizes="(max-width: 1024px) 60vw, 35vw" /></div><div className="relative col-span-2 mt-20 min-h-[440px] overflow-hidden rounded-2xl"><Image src="/images/parlovento-reception.png" alt="Recepción elegante bajo la palapa" fill className="object-cover" sizes="(max-width: 1024px) 40vw, 25vw" /></div></div></div></section>

    <section id="experiencias" className="bg-primary py-20 text-primary-foreground lg:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-accent">Tu celebración, a tu manera</p><h2 className="mt-3 max-w-2xl text-balance font-serif text-5xl font-semibold">De la primera idea al último brindis.</h2></div><p className="max-w-md leading-relaxed text-primary-foreground/70">Nos adaptamos a bodas, aniversarios, graduaciones, cumpleaños y encuentros que necesitan un escenario especial.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl bg-primary-foreground/15 md:grid-cols-3">{[ ["01","Imagina","Cuéntanos la fecha, invitados y la atmósfera que buscas."], ["02","Diseña","Elegimos contigo espacios, servicios y tiempos."], ["03","Celebra","Coordinamos el recinto para que estés presente en tu momento."] ].map(([n,t,d]) => <div key={n} className="bg-primary p-8"><span className="text-sm text-accent">{n}</span><h3 className="mt-12 font-serif text-3xl">{t}</h3><p className="mt-3 text-sm leading-relaxed text-primary-foreground/65">{d}</p></div>)}</div></div></section>

    <section id="paquetes" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Puntos de partida</p><h2 className="mt-4 text-balance font-serif text-5xl font-semibold">Una propuesta para cada forma de celebrar.</h2><p className="mt-4 leading-relaxed text-muted-foreground">Los paquetes son configuraciones iniciales. El precio final se define en tu cotización personalizada.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{packages.map((item) => <Card key={item.id} className={item.featured ? "border-primary bg-primary text-primary-foreground" : "bg-card"}><CardHeader><p className={item.featured ? "text-xs font-semibold uppercase tracking-[0.16em] text-accent" : "text-xs font-semibold uppercase tracking-[0.16em] text-primary"}>{item.featured ? "Más elegido" : "Parlovento"}</p><CardTitle className="font-serif text-3xl">{item.name}</CardTitle><CardDescription className={item.featured ? "text-primary-foreground/65" : undefined}>{item.description}</CardDescription></CardHeader><CardContent><ul className="flex flex-col gap-3">{item.inclusions.map((inclusion) => <li key={inclusion} className="flex items-start gap-3 text-sm"><Check className="mt-0.5 size-4 shrink-0 text-accent" />{inclusion}</li>)}</ul><Button onClick={openQuote} variant={item.featured ? "secondary" : "outline"} className="mt-8 w-full">Solicitar propuesta</Button></CardContent></Card>)}</div></section>

    <section id="preguntas" className="border-y bg-card"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[0.7fr_1.3fr] lg:px-8 lg:py-24"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Antes de visitarnos</p><h2 className="mt-4 font-serif text-5xl font-semibold">Preguntas frecuentes.</h2><p className="mt-4 text-muted-foreground">Si no encuentras la respuesta, abre el chat. Estamos para orientarte.</p></div><Accordion type="single" collapsible>{faqs.map((faq) => <AccordionItem key={faq.id} value={faq.id}><AccordionTrigger className="text-left text-base">{faq.question}</AccordionTrigger><AccordionContent className="leading-relaxed text-muted-foreground">{faq.answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>

    <section className="bg-accent py-20"><div className="mx-auto flex max-w-5xl flex-col items-center px-5 text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em]">Tu fecha puede empezar aquí</p><h2 className="mt-4 text-balance font-serif text-5xl font-semibold sm:text-6xl">Hagamos espacio para algo inolvidable.</h2><Button size="lg" onClick={openQuote} className="mt-8">Cotizar mi evento<ArrowRight data-icon="inline-end" /></Button></div></section>
    <footer className="bg-foreground text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-10 lg:flex-row lg:items-center lg:justify-between lg:px-8"><BrandMark light /><p className="text-sm text-primary-foreground/55">Salón jardín para eventos · México</p><div className="flex gap-5 text-sm text-primary-foreground/70"><Link href="/login">Acceso propietario</Link><a href="#preguntas">Preguntas</a></div></div></footer>
    <InquiryForm open={quoteOpen} onOpenChange={setQuoteOpen} /><ChatAssistant onQuote={openQuote} />
  </main>
}

function Feature({ icon: Icon, title, text }: { icon: typeof Users; title: string; text: string }) { return <div className="flex gap-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-secondary"><Icon className="size-4 text-primary" /></span><div><h3 className="font-medium">{title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{text}</p></div></div> }
